### ISSUE TITLE
[Submission]: Zoose Quantum Codespace

### ISSUE THREAD

**Issue by ianhellstrom** [qiskit-community/ecosystem#288]
### Github repo

https://github.com/ianhellstrom/zoose-codespace

### Description

GitHub Codespace template repository based on Zoose Quantum, a custom Docker image with everything included, so you can be up and running with any of the major quantum libraries (incl. Qiskit) with only two clicks! No installation required. Ideal for beginners or people who want to code quantum circuits on the go. Code quantum circuits straight in your browser with VSCode.

### Email

ian@databaseline.tech

### Alternatives

qBraid: commercial hosted notebooks

### License

MIT license

### Affiliations

None

### Tags

notebook

**Comment by javabster** [comment]
hi @ianhellstrom ! It's been a little while since your project joined the Ecosystem so I just wanted to check in and let you know of some follow up actions you can take to make the most of joining the program, if you're interested:

💬 Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)

🧠 Help us define the future of the Qiskit Ecosystem: we recently started an RFC on how the Ecosystem should be structured. It is very draft-y at the moment, but you can subscribe for notifications here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.

📣 Would you like to showcase your project to the Qiskit community? A couple of things you can do to raise awareness for your project:
- [write a blog for your project](https://github.com/qiskit-community/ecosystem/wiki/Write-a-Blog-for-your-Project) (reach out to Abby Mitchell via slack or [email](mailto:abby.s.mitchell@ibm.com) if you'd like to be featured on the Qiskit Medium)
- Participate in [Qiskit Demoday](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays). (reach out to Luciano Bello via slack or [email](mailto:BEL@zurich.ibm.com) to request a slot to demo your project)
Great having you as a part of the ecosystem! 🎉
