### ISSUE TITLE
[Submission]: RasQberry

### ISSUE THREAD

**Issue by JanLahmann** [qiskit-community/ecosystem#290]
### Github repo

https://github.com/JanLahmann/RasQberry

### Description

RasQberry is a functional model of IBM Quantum System One, and can run Qiskit on the integrated Raspberry Pi 

### Email

Jan.lahmann@de.ibm.com

### License

Apache License 2.0

### Tags

game

**Comment by javabster** [comment]
hi @JanLahmann! It's been a little while since your project joined the Ecosystem so I just wanted to check in and let you know of some follow up actions you can take to make the most of joining the program, if you're interested:

💬 Join other Qiskit ecosystem developers in the [Slack channel #qiskit-ecosystem](https://qiskit.slack.com/archives/C04RHE56N93) (if you are not in the Qiskit workspace yet, you can sign up here: https://qisk.it/join-slack)

🧠 Help us define the future of the Qiskit Ecosystem: we recently started an RFC on how the Ecosystem should be structured. It is very draft-y at the moment, but you can subscribe for notifications here https://github.com/Qiskit/RFCs/pull/42 to participate in that discussion.

📣 Would you like to showcase your project to the Qiskit community? A couple of things you can do to raise awareness for your project:
- [write a blog for your project](https://github.com/qiskit-community/ecosystem/wiki/Write-a-Blog-for-your-Project) (reach out to Abby Mitchell via slack or [email](mailto:abby.s.mitchell@ibm.com) if you'd like to be featured on the Qiskit Medium)
- Participate in [Qiskit Demoday](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays). (reach out to Luciano Bello via slack or [email](mailto:BEL@zurich.ibm.com) to request a slot to demo your project)

Great having you as a part of the ecosystem! 🎉
