### ISSUE TITLE
[Submission]: qBraid-SDK

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/ecosystem#440]
### Github repo

https://github.com/qBraid/qBraid

### Description

The qBraid-SDK is a Python toolkit for cross-framework abstraction, transpilation, and execution of quantum programs.

### Email

ryanhill@qbraid.com

### Alternatives

There are some alternatives to individual modules within the qBraid-SDK e.g. to execute a Qiskit circuit on an AWS device, you could use the qiskit-braket-provider. However, there aren't any other existing projects that support the same matrix of quantum program types and backends through a single, unified interface.

### License

GNU General Public License (GPL)

### Affiliations

qBraid Co.

### Tags

circuit, openqasm, converter

### Website

https://docs.qbraid.com/en/latest/sdk/overview.html

**Comment by mickahell** [comment]
Hi @ryanhill1 :) I re-created your issue du to breaking change on our sides.

It seems you have some broke dependancies, du to version conflicts with numpy

**Comment by ryanhill1** [comment]
@mickahell Hey there, thanks for re-opening!

Interesting it's throwing a dependency error... I can't seem to recreate on my side. I tried with a clean virtual environment using Python 3.10 and ran

```
pip install -r requirements.txt
pip install -r requirements-dev.txt
``` 

and seems to be ok? Didn't see any warnings either.. Do you have a link to the numpy dependency conflict message or know what packages are causing it?

**Comment by mickahell** [comment]
Sure no problem :)

In any way the PR has been created and you could be merged even with those requirements problem. Just the tests result gonna appear as false in the webpage until you corrected them.

**Comment by ryanhill1** [comment]
@mickahell I was able to recreate the error from the test locally, but I have a quick question about the testing installation procedure. It seems like it is getting past the requirements installs just fine, i.e. after

```bash
$ pip install -r requirements.txt
$ pip install -r requirements-dev.txt
```
there are no dependency conflicts. We end up with `qiskit-terra-0.24.1` and `numpy-1.23.5`, so the Cirq requirement of `numpy<1.24` is satisfied. But then, in the next part of the test, the actions execute

```bash
$ pip install --upgrade --force-reinstall qiskit-terra
```

We already have the latest version `qiskit-terra-0.24.1` installed, so that package is not effected. But in this process, it also forces a re-install + upgrade of `numpy`, moving it up to `numpy-1.25.0`. This obviously breaks the Cirq requirement mentioned above.

Could you help me understand what this additional step is doing? The latest version of  [qiskit-terra only requires numpy>=1.17](https://github.com/Qiskit/qiskit-terra/blob/e0c061d3f6cd6d5911be1bd1903a67d4a1c2d65a/requirements.txt#L2), and so before executing that upgrade line, there were no dependency conflicts. But after the extra pip force re-install upgrade, it not only breaks the `numpy` dependency with Cirq, but also breaks it with its own `qiskit-ibmq-provider-0.20.2` package (from latest release), which [also requires numpy<1.24](https://github.com/Qiskit/qiskit-ibmq-provider/blob/6d74592dcc4130b8ed1a20a4553a44d2d5011de7/requirements.txt#L4).

My question is, what is the purpose of the additional [`pip install --upgrade --force-reinstall qiskit-terra`](https://github.com/qiskit-community/ecosystem/actions/runs/5478420780/jobs/9978862554#step:6:68) after all of the dependencies from both requirements files have been installed? If this step is required for passing tests, can you provide any guidance on how can I make sure the upgrade leaves the numpy version alone?

**Comment by mickahell** [comment]
The reason we force the re-install of Terra is to make sure your project can run with the latest stable version. As Qiskit change pretty often it's one of our way to keep inform of breaking change for every project.

Indeed I'm agree this shouldn't have to upgrade numpy if it doesn't need.

@frankharkins do you have an idea of how to pass that ?

**Comment by ryanhill1** [comment]
@mickahell Oh ok, that makes sense. Adding the `--no-dependencies` / `--no-deps` flag performs the install and ignores package dependencies :

```bash
pip install --upgrade --no-dependencies --force-reinstall qiskit-terra
```

But should only really be used when you know that all other transitive dependencies are resolved. So in my case, it would fix the problem. But for others projects where dependencies are not already up-to-date with the latest qiskit requirements, it could potentially ignore dependency upgrades that it needs and break.

**Comment by mickahell** [comment]
FOr special case like this yours, you have to create a file `ecosystem.json` at the root of your project and put the configuration you need : see here : https://github.com/qiskit-community/ecosystem/blob/main/docs/project_overview.md#adding-project-to-the-ecosystem

**Comment by ryanhill1** [comment]
@mickahell Yes, I did add an [`ecosystem.json`](https://github.com/qBraid/qBraid/blob/87bd183e8f1262df7a6ea939c74c81b74d1ea050/ecosystem.json) file. Would adding an explicit upper bound `numpy<1.24` under "extra_depdencies" work?

**Comment by mickahell** [comment]
Oh sorry, I didn't saw it.

Oh indeed I was forgetting this field, yes try by adding it :)
If I'm remember well this allow to add package during the test run and so after the terra upgrade.

You can add it this way : `["numpy==1.*,<=1.24"]` if you want

**Comment by ryanhill1** [comment]
@mickahell Change made, should be good to go! https://github.com/qBraid/qBraid/commit/900bb3a98c54e19538a08ef75926e35b184f1de0

**Comment by mickahell** [comment]
Ok nice :) I don't have the permission to run wf, just wait for @frankharkins

**Comment by mickahell** [comment]
@ryanhill1 seems to not change the behaviour.
Anyway, we can still approve your project, for that I let @frankharkins decide and see next

**Comment by ryanhill1** [comment]
@mickahell Hmm ok. Well at least 2/3 done and not a numpy conflict this time! This is probably because the qiskit version in the requirements.txt is `qiskit~=0.43.2` which installs `qiskit-terra==0.24.1`, so would cause a conflict with the future `qiskit-terra==0.25.0`. It could probably be solved by loosening the qiskit requirement in qBraid? So instead of import `requirements.txt`, I might just update the `ecosystem.json` once more to allow for future versions

**Comment by mickahell** [comment]
In another project who has the requirements : `qiskit==0.43.0`

The dev tests pass with this log :
```bash
INFO ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
INFO qiskit 0.43.0 requires qiskit-terra==0.24.0, but you have qiskit-terra 0.25.0 which is incompatible.
INFO Successfully installed qiskit-terra-0.25.0
```

**Comment by mickahell** [comment]
The break seems to came from the `pytest qbraid/api qbraid/interface qbraid/transpiler qbraid/devices qbraid/tests` cmd and not the packages installation.

**Comment by ryanhill1** [comment]
@mickahell Ok, that's interesting. I'll see if I can recreate locally and get back to you.

Thank you for bearing with me through all of this, I appreciate your patience!

**Comment by ryanhill1** [comment]
@mickahell I was able to recreate the [dev tests error](https://github.com/qiskit-community/ecosystem/issues/440#issuecomment-1631358504) locally, and I think I've made changes that will finally allow all these tests to pass.

### Dev test error explanation

It turns out that it wasn't actually an issue with the pytests, but instead a regular version conflict error that was delayed until the package imports were collected for the tests. If you performed the qiskit-terra dev install without the "no dependencies" flag, then the following error is raised during the installation:

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qiskit 0.43.2 requires qiskit-terra==0.24.1, but you have qiskit-terra 0.25.0 which is incompatible.
```

Even though we do start the dev test with a [`pip uninstall -y qiskit-terra`](https://github.com/qiskit-community/ecosystem/blob/75cb025dff52c313535f3c814852e91fc8ed185c/ecosystem/manager.py#L543), the qiskit-metapackage is still installed with dependency requirement `qiskit-terra==0.24.1`, see [`setup.py`](https://github.com/Qiskit/qiskit-metapackage/blob/72ec6d208377fed3cc65851b775f90215cfa2c1e/setup.py#L27). So

```bash
pip install git+https://github.com/Qiskit/qiskit-terra.git@main
```
fails with the above dependency conflict error, while
```bash
pip install --no-dependencies git+https://github.com/Qiskit/qiskit-terra.git@main
```
passes, but will eventually raise an error during the pytest initialization when the conflicting packages are imported.

### Dev test fix & updates

I figured out that if I switched the qBraid-SDK `qiskit` requirement  to `qiskit-terra` and remove the version upper bounds, then the dependency conflict goes away, and all of the tests still pass: https://github.com/qBraid/qBraid/compare/main...qiskit-ecosystem-tests

Additionally, it *seems* like adding the explicit numpy version upper bound allows the install tests to pass without the `--no-dependencies` flag. At least it did for the dev tests.

I've pushed these tentative updates to a branch [`qBraid/qBraid@qiskit-ecosystem-test`](https://github.com/qBraid/qBraid/tree/qiskit-ecosystem-tests). Would it be possible to re-run the ecosystem tests targeting that branch?

**Comment by mickahell** [comment]
I tested in my branch and everything passed :) [Job log](https://github.com/mickahell/ecosystem/actions/runs/5542733187/jobs/10117794497)
If you only need what is inside terra this solution is pretty fine, but if you need other stuff like `Aer` this not gonna be a good solution to not used the metapackage `qiskit`.

Anyway your use case is pretty interesting to bench test our software ;)

**Comment by ryanhill1** [comment]
@mickahell Awesome!! Glad everything is finally passing! 🚀 

I've opened a PR https://github.com/qBraid/qBraid/pull/305 with the changes and can have that merged later today.

For now, qbraid doesn't use  qiskit-aer, so the switch to qiskit-terra is ok. Going forward there's a good chance it will need to be switched back, but that's a future problem for maybe 2-3 months from now.

Happy to be the tough test case! Thanks again for your responsiveness and for all your help 🙂

**Comment by mickahell** [comment]
Your welcome :)

The PR #447 still need to be validated and merged for passing, it probably be during next week and then we will reload the Action issue

**Comment by frankharkins** [comment]
Added to ecosystem in #452. Thanks both for your debugging work :)
